project_id = "qjfsxniavmgckkgaifmf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[rest]
enabled = true
port = 54323
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[realtime]
enabled = true
port = 54325

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.calendar-oauth]
verify_jwt = false