// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjfsxniavmgckkgaifmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqZnN4bmlhdm1nY2trZ2FpZm1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjE5NjgsImV4cCI6MjA3MTczNzk2OH0.wHKT2RnUrbG4Ljbf4mYqRpOKEZEXkdFwUArnEuRik54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});